name: ocetrac
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aiobotocore=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h3811e60_0
  - aioitertools=0.8.0=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - bokeh=2.4.0=py39hf3d152e_0
  - botocore=1.20.106=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py39h3811e60_1001
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cartopy=0.20.0=py39h13116ef_1
  - certifi=2021.5.30=py39hf3d152e_0
  - cffi=1.14.6=py39h4bc2ebd_1
  - cfitsio=3.470=hb418390_7
  - cftime=1.5.0=py39hce5d2b2_0
  - chardet=4.0.0=py39hf3d152e_1
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py39hf3d152e_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - curl=7.78.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39h3811e60_3
  - dask=2021.9.1=pyhd8ed1ab_0
  - dask-core=2021.9.1=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.4.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - distributed=2021.9.1=py39hf3d152e_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - geos=3.9.1=h9c3ff4c_2
  - gettext=0.19.8.1=h73d1719_1006
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_100
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - imagecodecs=2021.7.30=py39h44211f0_0
  - imageio=2.9.0=py_0
  - ipykernel=6.4.1=py39hef51801_0
  - ipython=7.27.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39hf3d152e_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jupyter_client=7.0.3=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py39hf3d152e_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.2=py39h1a9c180_0
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.4.2=h9c3ff4c_2
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgfortran-ng=11.2.0=h69a702a_8
  - libgfortran5=11.2.0=h5c6108e_8
  - libglib=2.68.4=h174f98d_1
  - libgomp=11.2.0=h1d223b6_8
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hed695b0_2
  - libpq=13.3=hd57d9b9_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - libtiff=4.3.0=hf544144_0
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.7=he1b5a44_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py39h3811e60_0
  - matplotlib=3.4.3=py39hf3d152e_0
  - matplotlib-base=3.4.3=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py39h1a9c180_1
  - multidict=5.1.0=py39h3811e60_1
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.7=nompi_py39h64b754b_102
  - networkx=2.3=py_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numcodecs=0.9.1=py39he80948d_0
  - numpy=1.21.2=py39hdbf815f_0
  - ocetrac=0.1.4=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py39hde0f152_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py39ha612740_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pooch=1.5.1=pyhd8ed1ab_0
  - proj=8.1.0=h277dcde_1
  - prompt-toolkit=3.0.20=pyha770c72_0
  - psutil=5.8.0=py39h3811e60_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.2.1=py39h1fd097d_0
  - pyqt=5.12.3=py39hf3d152e_7
  - pyqt-impl=5.12.3=py39h0fcd23e_7
  - pyqt5-sip=4.19.18=py39he80948d_7
  - pyqtchart=5.12=py39h0fcd23e_7
  - pyqtwebengine=5.12.1=py39h0fcd23e_7
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py39hf3d152e_3
  - python=3.9.7=hb7a2778_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py39hce5d2b2_3
  - pyyaml=5.4.1=py39h3811e60_1
  - pyzmq=22.3.0=py39h37b5a0c_0
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - s3fs=2021.8.1=pyhd8ed1ab_0
  - scikit-image=0.18.3=py39hde0f152_0
  - scipy=1.7.1=py39hee8e79c_0
  - setuptools=58.0.4=py39hf3d152e_1
  - shapely=1.7.1=py39ha61afbd_5
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.36.0=h9cd32fc_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - tifffile=2021.8.30=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - wrapt=1.12.1=py39h3811e60_3
  - xarray=0.19.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py39h3811e60_2
  - zarr=2.10.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_6
  - zict=2.0.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
prefix: /srv/conda/envs/ocetrac
